server:
  port: 10010
spring:
  application:
    name: api-gateway
#zuul:
#  routes:
#    user-service: # 这里是路由id，随意写
#      path: /user-service-gateway/** # 这里是映射路径
#      #url: http://127.0.0.1:8086 # 映射路径对应的实际url地址
#      serviceId: user-service # 指定服务名称

#???zuul????
zuul:
  retryable: true
  prefix: /api # 添加路由前缀
  routes:
    user-service: /user-service/** # 这里是映射路径


eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 2 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 6000 # 熔断超时时长：6000ms